/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqa;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author vansh
 */
public class Bus extends javax.swing.JFrame {
static ArrayList<String> schedule =new ArrayList<>();
Charger charger;
    /**
     * Creates new form Bus
     */
    public Bus() {
        initComponents();
        intro.setFont(new Font("Serif", Font.BOLD, 28));
        

    }

    Bus(Charger obj) {
         initComponents();
         intro.setFont(new Font("Serif", Font.BOLD, 28));
         this.charger= obj;
        
         
      //   slow.setText(set_Value(Working.slow_charger_schedule).toString());
         // fast.setText(Working.fast_charger_schedule.toString());
        
         //To change body of generated methods, choose Tools | Templates.
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        intro.setText("BUS TRANSIT SYSTEM:");

        jButton1.setText("Previous");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Schedule");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton2ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(intro, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton2)
                        .addGap(216, 216, 216)
                        .addComponent(jButton1)))
                .addContainerGap(647, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(intro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	 
    	 


charger.setVisible(true);
 System.out.println(charger.item);
charger.Manufacturer.setSelectedIndex(charger.item.get(0));
charger.battery_selector.setSelectedIndex(charger.item.get(1));
charger.bus_price.setText(charger.item.get(2)+"");
charger.charger1_manufacturer.setSelectedIndex(charger.item.get(3));
charger.charger1_capacity.setSelectedIndex(charger.item.get(4));
charger.charger1_price.setText(charger.item.get(5)+"");
charger.charger2_manufaturer.setSelectedIndex(charger.item.get(6));
charger.charger2_capacity.setSelectedIndex(charger.item.get(7));
charger.charger2_price.setText(charger.item.get(8)+"");
charger.Total_buses.setText(charger.item.get(9)+"");
charger.portW.setText(charger.item.get(10)+"");
charger.portE.setText(charger.item.get(11)+"");
charger.intransit.setText(charger.item.get(12)+"");
charger.Total_charger.setText(charger.item.get(13)+"");
charger.number_Slow.setText(charger.item.get(14)+"");
charger.number_fast.setText(charger.item.get(15)+"");
charger.Total_charger_price.setText(charger.item.get(16)+"");
charger.Total_price.setText(charger.item.get(17)+"");
 

this.dispose();
 

 
  
 
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException, IOException {//GEN-FIRST:event_jButton2ActionPerformed
     fileGetter();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    public  void fileGetter() throws FileNotFoundException, IOException{
		 
        
      JFileChooser fc = new JFileChooser();
    JFrame frame = new JFrame();
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

     
    
      int returnVal = fc.showOpenDialog(frame);
      if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();
        try {
          BufferedReader input = new BufferedReader(new InputStreamReader(
              new FileInputStream(file)));
          jTextArea1.read(input, "READING FILE :-)");
        } catch (Exception e) {
          e.printStackTrace();
        }
      } else {
        System.out.println("Operation is CANCELLED :(");
     }
//     
     }
    /**
     * @param args the command line arguments
     */
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel intro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
